### ISSUE TITLE
panic on typed primitives that implement error interface

### ISSUE THREAD

**Issue by Melaninneal** [go-test/deep#31]
doing a deep equal on errors often panics on reflect calls 

`&url.Error{
					Op: "parse",
					URL: "http:// invalid.url.com/path?unencoded=true",
					Err: url.InvalidHostError(" "),
				}`

**Comment by daniel-nichter** [comment]
Thanks for the bug report. I'll try to create a test case with that example.

**Comment by daniel-nichter** [comment]
Real issue is https://golang.org/pkg/net/url/#InvalidHostError
It's a string that implements the error interface.

**Comment by daniel-nichter** [comment]
Fixed in master. Will be released in v1.0.3.
