### ISSUE TITLE
No longer able to do a deep comparison on the "github.com/pkg/errors" library

### ISSUE THREAD

**Issue by Melaninneal** [go-test/deep#34]
The following code snippet now panics. Used to work with v1.0.1 and older

```go
package main

import (
	"fmt"
	"github.com/go-test/deep"
	"github.com/pkg/errors"
)

func main() {
	fmt.Println(
		deep.Equal(
			errors.Wrap(
				errors.New("test error"), "wrapper"),
			errors.Wrap(
				errors.New("test error"), "wrapper"),
		),
	)
}

**Comment by daniel-nichter** [comment]
Was fixed in master but not released. Just tagged and released as v1.0.3.

I tested it before and after, so it should work. If not, let me know and we'll re-open this issue.
