### ISSUE TITLE
 fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by nickdooley2016** [go-test/deep#51]
Is recursion causing this?

fatal error: concurrent map read and map write

goroutine 213 [running]:
runtime.throw({0x9fc28f, 0x45d4d9})
	C:/Program Files/Go/src/runtime/panic.go:1198 +0x71 fp=0xc000546af8 sp=0xc000546ac8 pc=0x4337b1
runtime.mapaccess2(0xc0b963e1a0, 0xc015228750, 0xc0092a2f00)
	C:/Program Files/Go/src/runtime/map.go:469 +0x205 fp=0xc000546b38 sp=0xc000546af8 pc=0x40e2e5
reflect.mapaccess(0x943740, 0xc0b963e1a0, 0xc0bfa7db80)
	C:/Program Files/Go/src/runtime/map.go:1318 +0x19 fp=0xc000546b60 sp=0xc000546b38 pc=0x45d259
reflect.Value.MapIndex({0x962de0, 0xc009245ad0, 0xc000546e60}, {0x943740, 0xc0b963e1a0, 0x98})
	C:/Program Files/Go/src/reflect/value.go:1530 +0xe5 fp=0xc000546bd0 sp=0xc000546b60 pc=0x495aa5
github.com/go-test/deep.(*cmp).equals(0xc000547430, {0x962de0, 0xc0092459e0, 0x95}, {0x962de0, 0xc009245ad0, 0x95}, 0x1)
	C:/Users/work/go/pkg/mod/github.com/go-test/deep@v1.0.8/deep.go:350 +0x32a8 fp=0xc000546f98 sp=0xc000546bd0 pc=0x8c6a48
github.com/go-test/deep.(*cmp).equals(0xc000547430, {0x9d9ac0, 0xc009245950, 0x99}, {0x9d9ac0, 0xc009245a40, 0x99}, 0x0)
	C:/Users/work/go/pkg/mod/github.com/go-test/deep@v1.0.8/deep.go:287 +0x2893 fp=0xc000547360 sp=0xc000546f98 pc=0x8c6033
github.com/go-test/deep.EqualNew({0x9d9ac0, 0xc009245950}, {0x9d9ac0, 0xc009245a40})
	C:/Users/work/go/pkg/mod/github.com/go-test/deep@v1.0.8/deep.go:141 +0x347 fp=0xc0005474a0 sp=0xc000547360 pc=0x8c35c7

**Comment by daniel-nichter** [comment]
Can you provide a test case for this? Perhaps it's due to parallel test runs. This error has never been reported before.

**Comment by daniel-nichter** [comment]
Please reopen if you can reproduce this in a test case.
